import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body
        className='px-[20px] lg:px-[50px]'
        style={{ fontFamily: 'Poppins-regular' }}
      >
        <Navbar />
        {children}
      </body>
    </html>
  )
}
